#ifndef __TINY_TOOLKIT__COMMON__MACRO__H__
#define __TINY_TOOLKIT__COMMON__MACRO__H__


/**
 *
 *  作者: hm
 *
 *  说明: 宏定义
 *
 */


#include "platform.h"


#define TINY_TOOLKIT_PI								3.1415926535898f


#define TINY_TOOLKIT_SECOND							(1)
#define TINY_TOOLKIT_MINUTE							(60 * TINY_TOOLKIT_SECOND)
#define TINY_TOOLKIT_HOUR							(60 * TINY_TOOLKIT_MINUTE)
#define TINY_TOOLKIT_DAY							(24 * TINY_TOOLKIT_HOUR)
#define TINY_TOOLKIT_WEEK							(7 * TINY_TOOLKIT_DAY)
#define TINY_TOOLKIT_YEAR							(12 * TINY_TOOLKIT_WEEK)


#define TINY_TOOLKIT_BYTE							(1)  /// Byte
#define TINY_TOOLKIT_KB								(1024 * TINY_TOOLKIT_BYTE)  /// Kilobyte
#define TINY_TOOLKIT_MB								(1024 * TINY_TOOLKIT_KB)  /// Mega byte
#define TINY_TOOLKIT_GB								(1024 * TINY_TOOLKIT_MB)  /// Giga byte
#define TINY_TOOLKIT_TB								(1024 * TINY_TOOLKIT_GB)  /// Tera byte
#define TINY_TOOLKIT_PB								(1024 * TINY_TOOLKIT_TB)  /// Peta byte
#define TINY_TOOLKIT_EB								(1024 * TINY_TOOLKIT_PB)  /// Exa byte
#define TINY_TOOLKIT_ZB								(1024 * TINY_TOOLKIT_EB)  /// Zetta byte
#define TINY_TOOLKIT_YB								(1024 * TINY_TOOLKIT_ZB)  /// Yotta byte
#define TINY_TOOLKIT_BB								(1024 * TINY_TOOLKIT_YB)  /// Bronto byte
#define TINY_TOOLKIT_NB								(1024 * TINY_TOOLKIT_BB)  /// Nona byte
#define TINY_TOOLKIT_DB								(1024 * TINY_TOOLKIT_NB)  /// Dogga byte


#define TINY_TOOLKIT_CONSOLE_RESET					"\033[0m"  /// 关闭所有属性
#define TINY_TOOLKIT_CONSOLE_HIGH_LIGHT				"\033[1m"  /// 高亮度
#define TINY_TOOLKIT_CONSOLE_DARK					"\033[2m"
#define TINY_TOOLKIT_CONSOLE_UNDER_LINE				"\033[4m"  /// 下划线
#define TINY_TOOLKIT_CONSOLE_BLINK					"\033[5m"  /// 闪烁
#define TINY_TOOLKIT_CONSOLE_REVERSE				"\033[7m"  /// 反显
#define TINY_TOOLKIT_CONSOLE_CONCEALED				"\033[8m"  /// 消隐
#define TINY_TOOLKIT_CONSOLE_CLEAR_LINE				"\033[K"   /// 清除从光标到行尾的内容


#define TINY_TOOLKIT_CONSOLE_FOREGROUND_BALCK		"\033[30m"  /// 黑色
#define TINY_TOOLKIT_CONSOLE_FOREGROUND_RED			"\033[31m"  /// 红色
#define TINY_TOOLKIT_CONSOLE_FOREGROUND_GREEN		"\033[32m"  /// 绿色
#define TINY_TOOLKIT_CONSOLE_FOREGROUND_YELLOW		"\033[33m"  /// 黄色
#define TINY_TOOLKIT_CONSOLE_FOREGROUND_BLUE		"\033[34m"  /// 蓝色
#define TINY_TOOLKIT_CONSOLE_FOREGROUND_MAGENTA		"\033[35m"  /// 紫色
#define TINY_TOOLKIT_CONSOLE_FOREGROUND_CYAN		"\033[36m"  /// 深绿色
#define TINY_TOOLKIT_CONSOLE_FOREGROUND_WHITE		"\033[37m"  /// 白色


#define TINY_TOOLKIT_CONSOLE_BACKGROUND_BALCK		"\033[40m"  /// 黑色
#define TINY_TOOLKIT_CONSOLE_BACKGROUND_RED			"\033[41m"  /// 红色
#define TINY_TOOLKIT_CONSOLE_BACKGROUND_GREEN		"\033[42m"  /// 绿色
#define TINY_TOOLKIT_CONSOLE_BACKGROUND_YELLOW		"\033[43m"  /// 黄色
#define TINY_TOOLKIT_CONSOLE_BACKGROUND_BLUE		"\033[44m"  /// 蓝色
#define TINY_TOOLKIT_CONSOLE_BACKGROUND_MAGENTA		"\033[45m"  /// 紫色
#define TINY_TOOLKIT_CONSOLE_BACKGROUND_CYAN		"\033[46m"  /// 深绿色
#define TINY_TOOLKIT_CONSOLE_BACKGROUND_WHITE		"\033[47m"  /// 白色


#if TINY_TOOLKIT_PLATFORM == TINY_TOOLKIT_PLATFORM_APPLE
#
#  define TINY_TOOLKIT_EOL "\r"
#
#  define TINY_TOOLKIT_FILE __FILE__
#  define TINY_TOOLKIT_LINE __LINE__
#  define TINY_TOOLKIT_FUNC __PRETTY_FUNCTION__
#
#  define TINY_TOOLKIT_FOLDER_SEP "/"
#
#elif TINY_TOOLKIT_PLATFORM == TINY_TOOLKIT_PLATFORM_WINDOWS
#
#  define TINY_TOOLKIT_EOL "\r\n"
#
#  define TINY_TOOLKIT_FILE __FILE__
#  define TINY_TOOLKIT_LINE __LINE__
#  define TINY_TOOLKIT_FUNC __FUNCTION__
#
#  define TINY_TOOLKIT_FOLDER_SEP "\\"
#
#else
#
#  define TINY_TOOLKIT_EOL "\n"
#
#  define TINY_TOOLKIT_FILE __FILE__
#  define TINY_TOOLKIT_LINE __LINE__
#  define TINY_TOOLKIT_FUNC __PRETTY_FUNCTION__
#
#  define TINY_TOOLKIT_FOLDER_SEP "/"
#
#endif


#endif // __TINY_TOOLKIT__COMMON__MACRO__H__
