#
# 遍历指定目录获取文件, TRAVERSE_FILE(arg path type)
#
MACRO(TRAVERSE_FILE)

	IF(NOT ${ARGC} LESS 4)

		MESSAGE(FATAL_ERROR "ARGC NUMBER ERROR")

	ENDIF()

	FILE(GLOB_RECURSE ${ARGV0}	"${ARGV1}/${ARGV2}")

	FOREACH(file ${${ARGV0}})

		MESSAGE(STATUS "Found File : " ${file})

	ENDFOREACH()

ENDMACRO(TRAVERSE_FILE)