#
# 包含多个头文件目录, TRAVERSE_INCLUDE(name1 name2 ...)
#
MACRO(TRAVERSE_INCLUDE)

	FOREACH(param ${ARGN})

		INCLUDE_DIRECTORIES(${param})

	ENDFOREACH()

ENDMACRO(TRAVERSE_INCLUDE)


#
# 根据项目名包含多个头文件目录, TRAVERSE_INCLUDE_FOR_PROGRAM_NAME(name1 name2 ...)
#
MACRO(TRAVERSE_INCLUDE_FOR_PROGRAM_NAME)

	FOREACH(param ${ARGN})

		TARGET_INCLUDE_DIRECTORIES(${PROGRAM_NAME}	PUBLIC	${param})

	ENDFOREACH()

ENDMACRO(TRAVERSE_INCLUDE_FOR_PROGRAM_NAME)
