#
# 包含多个链接, TRAVERSE_LIBRARY_FOR_PROGRAM_NAME(name1 name2 ...)
#
MACRO(TRAVERSE_LIBRARY_FOR_PROGRAM_NAME)

	FOREACH(param ${ARGN})

		TARGET_LINK_LIBRARIES(${PROGRAM_NAME}	PUBLIC	${param})

	ENDFOREACH()

ENDMACRO(TRAVERSE_LIBRARY_FOR_PROGRAM_NAME)
