#
# 遍历递归指定目录获取源文件定义分组, RECURSE_DIRECTORY_SOURCE_FILE_GROUP(group path)
#
MACRO(RECURSE_DIRECTORY_SOURCE_FILE_GROUP)

	IF(NOT ${ARGC} EQUAL 2)

		MESSAGE(FATAL_ERROR "There is two and only two parameter")

	ENDIF()

	RECURSE_DIRECTORY_SOURCE_FILE(GROUP_FILES ${ARGV1})

	SOURCE_GROUP(${ARGV0} FILES ${GROUP_FILES})

ENDMACRO(RECURSE_DIRECTORY_SOURCE_FILE_GROUP)


#
# 遍历递归当前目录获取源文件定义分组, RECURSE_CURRENT_DIRECTORY_SOURCE_FILE_GROUP(group)
#
MACRO(RECURSE_CURRENT_DIRECTORY_SOURCE_FILE_GROUP)

	IF(NOT ${ARGC} EQUAL 1)

		MESSAGE(FATAL_ERROR "There is one and only one parameter")

	ENDIF()

	RECURSE_DIRECTORY_SOURCE_FILE_GROUP(${ARGV0} ${CMAKE_CURRENT_LIST_DIR})

ENDMACRO(RECURSE_CURRENT_DIRECTORY_SOURCE_FILE_GROUP)


#
# 遍历指定目录获取源文件定义分组, TRAVERSE_DIRECTORY_SOURCE_FILE_GROUP(group path)
#
MACRO(TRAVERSE_DIRECTORY_SOURCE_FILE_GROUP)

	IF(NOT ${ARGC} EQUAL 2)

		MESSAGE(FATAL_ERROR "There is two and only two parameter")

	ENDIF()

	TRAVERSE_DIRECTORY_SOURCE_FILE(GROUP_FILES ${ARGV1})

	SOURCE_GROUP(${ARGV0} FILES ${GROUP_FILES})

ENDMACRO(TRAVERSE_DIRECTORY_SOURCE_FILE_GROUP)


#
# 遍历当前目录获取源文件定义分组, TRAVERSE_CURRENT_DIRECTORY_SOURCE_FILE_GROUP(group)
#
MACRO(TRAVERSE_CURRENT_DIRECTORY_SOURCE_FILE_GROUP)

	IF(NOT ${ARGC} EQUAL 1)

		MESSAGE(FATAL_ERROR "There is one and only one parameter")

	ENDIF()

	TRAVERSE_DIRECTORY_SOURCE_FILE_GROUP(${ARGV0} ${CMAKE_CURRENT_LIST_DIR})

ENDMACRO(TRAVERSE_CURRENT_DIRECTORY_SOURCE_FILE_GROUP)