#
# 遍历指定目录获取源文件, TRAVERSE_SOURCE_FILE(arg path)
#
MACRO(TRAVERSE_SOURCE_FILE)

	IF(NOT ${ARGC} EQUAL 2)

		MESSAGE(FATAL_ERROR "ARGC NUMBER ERROR")

	ENDIF()

	FILE(GLOB_RECURSE ${ARGV0}	"${ARGV1}/*.c"
								"${ARGV1}/*.cc"
								"${ARGV1}/*.cpp"
								"${ARGV1}/*.h"
								"${ARGV1}/*.hh"
								"${ARGV1}/*.hpp")

ENDMACRO(TRAVERSE_SOURCE_FILE)


#
# 遍历当前目录获取源文件, TRAVERSE_CURRENT_SOURCE_FILE(arg)
#
MACRO(TRAVERSE_CURRENT_SOURCE_FILE)

	IF(NOT ${ARGC} EQUAL 1)

		MESSAGE(FATAL_ERROR "ARGC NUMBER ERROR")

	ENDIF()

	TRAVERSE_SOURCE_FILE(${ARGV0} ${CMAKE_CURRENT_LIST_DIR})

ENDMACRO(TRAVERSE_CURRENT_SOURCE_FILE)
