#
# 检测安装路径
#
IF(NOT CMAKE_INSTALL_PREFIX)

	IF(WIN32)

		SET(CMAKE_INSTALL_PREFIX "/usr")

	ELSE()

		SET(CMAKE_INSTALL_PREFIX "C:\\")

	ENDIF()

ENDIF()


#
# 设置安装路径
#
IF (CMAKE_INSTALL_PREFIX STREQUAL "/usr" OR
	CMAKE_INSTALL_PREFIX STREQUAL "/usr/" OR
	CMAKE_INSTALL_PREFIX STREQUAL "/usr/local" OR
	CMAKE_INSTALL_PREFIX STREQUAL "/usr/local/")

	SET(BINARY_INSTALL_PREFIX ${CMAKE_INSTALL_PREFIX}/bin)
	SET(LIBRARY_INSTALL_PREFIX ${CMAKE_INSTALL_PREFIX}/lib64)
	SET(INCLUDE_INSTALL_PREFIX ${CMAKE_INSTALL_PREFIX}/include/tinyToolkit)

	SET(EXTRA_BINARY_INSTALL_PREFIX ${CMAKE_INSTALL_PREFIX}/bin)
	SET(EXTRA_LIBRARY_INSTALL_PREFIX ${CMAKE_INSTALL_PREFIX}/lib64)
	SET(EXTRA_INCLUDE_INSTALL_PREFIX ${CMAKE_INSTALL_PREFIX}/include/tinyToolkit-extra)

ELSE()

	SET(BINARY_INSTALL_PREFIX ${CMAKE_INSTALL_PREFIX}/bin)
	SET(LIBRARY_INSTALL_PREFIX ${CMAKE_INSTALL_PREFIX}/lib64)
	SET(INCLUDE_INSTALL_PREFIX ${CMAKE_INSTALL_PREFIX}/include)

	SET(EXTRA_BINARY_INSTALL_PREFIX ${CMAKE_INSTALL_PREFIX}/bin)
	SET(EXTRA_LIBRARY_INSTALL_PREFIX ${CMAKE_INSTALL_PREFIX}/lib64)
	SET(EXTRA_INCLUDE_INSTALL_PREFIX ${CMAKE_INSTALL_PREFIX}/include-extra)

ENDIF()


#
# 打印安装路径
#
MESSAGE(STATUS "Install tinyToolkit       binary  prefix : " ${BINARY_INSTALL_PREFIX})
MESSAGE(STATUS "Install tinyToolkit       library prefix : " ${LIBRARY_INSTALL_PREFIX})
MESSAGE(STATUS "Install tinyToolkit       include prefix : " ${INCLUDE_INSTALL_PREFIX})

MESSAGE(STATUS "Install tinyToolkit-extra binary  prefix : " ${EXTRA_BINARY_INSTALL_PREFIX})
MESSAGE(STATUS "Install tinyToolkit-extra library prefix : " ${EXTRA_LIBRARY_INSTALL_PREFIX})
MESSAGE(STATUS "Install tinyToolkit-extra include prefix : " ${EXTRA_INCLUDE_INSTALL_PREFIX})
